version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
      - npm install -g aws-cdk
  build:
    commands:
      - npm run build
      - npx cdk synth

artifacts:
  files:
    - '**/*'
    - 'cdk.out/**/*'
